---@type dotvim.core.plugin.PluginOption[]
return {
  {
    "tzachar/local-highlight.nvim",
    event = { "BufReadPost", "BufNewFile" },
    opts = {
      hlgroup = "IlluminatedWordWrite",
      disable_file_types = {
        "nuipopup",
        "rightclickpopup",
        "NvimTree",
        "help",
        "noice",
        "neo-tree",
        "startify",
        "NvimTree",
        "packer",
        "alpha",
        "nuipopup",
        "toggleterm",
        "noice",
        "crates.nvim",
        "lazy",
        "Trouble",
        "rightclickpopup",
        "TelescopePrompt",
        "Glance",
        "DressingInput",
        "lspinfo",
        "nofile",
        "mason",
        "Outline",
        "aerial",
        "flutterToolsOutline",
        "neo-tree",
        "neo-tree-popup",
        "fzf",
      },
    },
  },
}
