local function default_data_path()
  return vim.fn.stdpath("data") .. "/dotvim_data"
end

local configs = {
  data_root = (function()
    -- try to load data path from marker file
    local marker_file = vim.fn.stdpath("config") .. "/dotvim/DATA_ROOT"
    local content = require("dotvim.commons.fs").read_file(marker_file)
    if content == nil then
      return default_data_path()
    end
    local path = vim.trim(content)
    if path == "" then
      return default_data_path()
    end
    return path
  end)(),
}

_G["dotvim_dataroot"] = configs.data_root
_G["dotvim_lazyroot"] = configs.data_root .. "/lazy"

local function install_missing_lazy()
  local lazypath = configs.data_root .. "/lazy/lazy.nvim"
  ---@diagnostic disable-next-line: undefined-field
  if not vim.uv.fs_stat(lazypath) then
    vim.fn.system {
      "git",
      "clone",
      "--filter=blob:none",
      "https://github.com/folke/lazy.nvim.git",
      "--branch=stable", -- latest stable release
      lazypath,
    }
  end
  ---@diagnostic disable-next-line: undefined-field
  vim.opt.rtp:prepend(lazypath)
end

-- set mapleader at very beginning of profile
vim.api.nvim_set_var("mapleader", " ")

install_missing_lazy()

require("lazy").setup {
  root = _G.dotvim_lazyroot, -- directory where plugins will be installed
  lockfile = _G.dotvim_dataroot .. "/lazy-lock.json", -- lockfile generated by lazy.nvim
  git = {
    timeout = 600,
  },
  spec = {
    { import = "dotvim.plugins" },
    { import = "dotvim.plugins.langs" },
  },
  performance = {
    cache = { enabled = true },
    rtp = {
      paths = {
        os.getenv("HOME") .. "/.dotvim",
      },
      disabled_plugins = {
        "gzip",
        "matchit",
        "matchparen",
        "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
        "spellfile",
      },
    },
  },
}

require("dotvim.configs")
