local function default_data_path()
  return vim.fn.stdpath("data") .. "/dotvim_data"
end

local function default_theme()
  return "catppuccin"
end

local function get_config_value(key, default_fn)
  local marker_file = vim.fn.stdpath("config") .. "/dotvim/" .. key:upper()
  local content = require("dotvim.commons.fs").read_file(marker_file)
  if content == nil then
    return default_fn()
  end
  local value = vim.trim(content)
  if value == "" then
    return default_fn()
  end
  return value
end

_G["DOTVIM_data_root"] = get_config_value("data_root", default_data_path)
_G["DOTVIM_theme"] = get_config_value("theme", default_theme)
_G["DOTVIM_lazy_root"] = DOTVIM_data_root .. "/lazy"

local function install_missing_lazy()
  local lazypath = DOTVIM_lazy_root .. "/lazy.nvim"
  ---@diagnostic disable-next-line: undefined-field
  if not vim.uv.fs_stat(lazypath) then
    vim.fn.system {
      "git",
      "clone",
      "--filter=blob:none",
      "https://github.com/folke/lazy.nvim.git",
      "--branch=stable", -- latest stable release
      lazypath,
    }
  end
  ---@diagnostic disable-next-line: undefined-field
  vim.opt.rtp:prepend(lazypath)
end

-- set mapleader at very beginning of profile
vim.api.nvim_set_var("mapleader", " ")

install_missing_lazy()

require("lazy").setup {
  root = DOTVIM_lazy_root, -- directory where plugins will be installed
  lockfile = DOTVIM_data_root .. "/lazy-lock.json", -- lockfile generated by lazy.nvim
  git = {
    timeout = 600,
  },
  spec = {
    { import = "dotvim.plugins" },
    { import = "dotvim.plugins.ai" },
    { import = "dotvim.plugins.base" },
    { import = "dotvim.plugins.coding" },
    { import = "dotvim.plugins.edit" },
    { import = "dotvim.plugins.langs" },
    { import = "dotvim.plugins.lsp" },
    { import = "dotvim.plugins.pairs" },
    { import = "dotvim.plugins.theme" },
    { import = "dotvim.plugins.treesitter" },
    { import = "dotvim.plugins.ui" },
  },
  performance = {
    cache = { enabled = true },
    rtp = {
      paths = {
        os.getenv("HOME") .. "/.dotvim",
      },
      disabled_plugins = {
        "gzip",
        "matchit",
        "matchparen",
        "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
        "spellfile",
      },
    },
  },
}

require("dotvim.configs")
