---@type dora.core.plugin.PluginOption[]
return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = true,
    build = ":CatppuccinCompile",
    opts = {
      flavour = "frappe",
      term_colors = true,
      transparent_background = false,
      compile_path = vim.fn.stdpath("cache") .. "/catppuccin",
      dim_inactive = { enabled = false },
      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        properties = {},
        functions = {},
        keywords = {},
        operators = {},
        loops = {},
        booleans = {},
        numbers = {},
        types = {},
        strings = {},
        variables = {},
      },
      custom_highlights = function(C)
        return {
          ["@lsp.typemod.variable.mutable.rust"] = { style = { "underline" } },
          ["@lsp.typemod.selfKeyword.mutable.rust"] = {
            style = { "underline" },
          },
          ["@variable.builtin"] = { fg = C.maroon, style = { "italic" } },
          NormalFloat = { fg = C.text, bg = C.none },
          NoicePopup = { fg = C.text, bg = C.none },
          NormalNC = { fg = C.text, bg = C.none },
          NoiceGuiDocPopupBorder = { fg = C.base, bg = C.none },
        }
      end,
      integrations = {
        alpha = true,
        aerial = true,
        barbecue = {
          dim_dirname = true,
          bold_basename = true,
        },
        treesitter = true,
        headlines = true,
        flash = true,
        gitsigns = true,
        notify = true,
        native_lsp = {
          enabled = true,
          virtual_text = {
            errors = { "italic" },
            hints = { "italic" },
            warnings = { "italic" },
            information = { "italic" },
          },
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
        semantic_tokens = true,
        lsp_trouble = true,
        markdown = true,
        noice = true,
        telescope = {
          enabled = true,
          style = "nvchad",
        },
        illuminate = true,
        nvimtree = false,
        mason = true,
        neotree = true,
        mini = true,
        which_key = true,
        hop = true,
        cmp = true,
        lsp_saga = true,
        octo = true,
        navic = { enabled = true },
        window_picker = true,
      },
    },
    actions = {
      {
        id = "catppuccin.compile",
        callback = "CatppuccinCompile",
        description = "Recompile Catppuccin",
        from = "catppuccin.nvim",
        category = "Catppuccin",
      },
    },
  },
}
