name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.os }} ${{ matrix.flavor }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        flavor: [v0.11.0, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup neovim ${{ matrix.flavor }}
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.flavor }}
      - uses: extractions/setup-just@v3
      - name: Run tests
        run: |
          just test
        
